# Generated by Django 5.2.1 on 2025-05-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_pdffile_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdffile',
            name='keywords',
            field=models.JSONField(default=list),
        ),
    ]
