# Generated by Django 4.2.23 on 2025-09-02 05:34

from django.conf import settings
import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_folder_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdffile',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pdffile',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AlterField(
            model_name='folder',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pdffile',
            name='keywords',
            field=models.JSONField(default=list),
        ),
        migrations.AddIndex(
            model_name='pdffile',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='core_pdffil_search__1650a6_gin'),
        ),
    ]
