# Generated by Django 4.2.23 on 2025-09-03 09:57
# Fixed for SQLite compatibility using SeparateDatabaseAndState

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Migration 0007: Remove PostgreSQL-specific search fields and add text_content.
    
    Root Cause Fix:
    ---------------
    Migration 0006 added a SearchVectorField with a GIN index. On PostgreSQL,
    both the field and index are created. On SQLite, the GIN index creation
    is silently skipped (PostgreSQL-specific), BUT Django's migration state
    still records that the index exists.
    
    When this migration tries to remove the search_vector field, SQLite's
    schema editor attempts to rebuild the table and checks Django's state
    which claims an index exists - causing the error:
    "error in index core_pdffil_search__1650a6_gin after drop column"
    
    Solution:
    ---------
    Use SeparateDatabaseAndState to:
    1. On PostgreSQL: Run all operations normally (index exists, remove it)
    2. On SQLite: Only update state for index removal (index never existed)
       Then run the field operations normally.
    """

    dependencies = [
        ('core', '0006_pdffile_content_pdffile_search_vector_and_more'),
    ]

    operations = [
        # Step 1: Remove index - use SeparateDatabaseAndState
        # On PostgreSQL, this removes the actual index
        # On SQLite, we only update state (index was never created)
        migrations.SeparateDatabaseAndState(
            state_operations=[
                # Update Django's state to remove the index
                migrations.RemoveIndex(
                    model_name='pdffile',
                    name='core_pdffil_search__1650a6_gin',
                ),
            ],
            database_operations=[
                # Only run on PostgreSQL - on SQLite index was never created
                migrations.RunSQL(
                    sql=[
                        # PostgreSQL: drop the index if it exists
                        ('DROP INDEX IF EXISTS "core_pdffil_search__1650a6_gin"', []),
                    ],
                    reverse_sql=[],  # No reverse needed
                ),
            ],
        ),
        
        # Step 2: Remove fields and add new one
        # These work on both SQLite and PostgreSQL
        migrations.RemoveField(
            model_name='pdffile',
            name='content',
        ),
        migrations.RemoveField(
            model_name='pdffile',
            name='search_vector',
        ),
        migrations.AddField(
            model_name='pdffile',
            name='text_content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='pdffile',
            name='keywords',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
