# Generated by Django 4.2.23 on 2025-09-15 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_customuser_department_alter_customuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='parent',
        ),
    ]
