# Generated by Django 4.2.23 on 2025-10-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_folder_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='keywords',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
